[package]
name = "mtsc"
version = "4.4.4"
edition = "2018"
authors = ["S. Beeblebrox"] # <you@example.com>
license = "MIT"

[dependencies]
v8 = "0.34.0"
clap = "2.33.3"

[build-dependencies]
reqwest = "0.11.6"
tokio = { version = "1.14.0", features = ["full"] }