[package]
name = "mtsc"
version = "4.4.4"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
v8 = "0.34.0"
clap = "2.33.3"

[build-dependencies]
#downloader = "0.2.6"
reqwest = "0.11.6"
tokio = { version = "1.14.0", features = ["full"] }