[package]
name = "stc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
v8 = "0.34.0"
downloader = "0.2.6"
semver = "1.0.4"
clap = "2.33.3"